find_path(OPENCL_INCLUDE_DIR
  NAMES OpenCL/cl.h
        CL/cl.h
  PATHS /usr/include)
  
find_library(OPENCL_LIBRARY OpenCL
  PATHS ENV OCLROOT
        ENV AMDAPPSDKROOT
        ENV CUDA_PATH
        ENV INTELOCLSDKROOT)  
        
if(OPENCL_INCLUDE_DIR AND OPENCL_LIBRARY)
  set(FOUND_OPENCL 1 CACHE BOOL "Found OpenCL")
else(OPENCL_INCLUDE_DIR AND OPENCL_LIBRARY)
  message(ERROR "OPENCL not found")
  set(FOUND_OPENCL 0 CACHE BOOL "Not found OpenCL")
endif(OPENCL_INCLUDE_DIR AND OPENCL_LIBRARY)

mark_as_advanced(OPENCL_INCLUDE_DIR OPENCL_LIBRARY FOUND_OPENCL)