.TH "BuildProgram" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BuildProgram \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDeviceParameters\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfilename\fP"
.br
.ti -1c
.RI "std::string \fBsource\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
