.TH "BayerFilter/BayerFilter Directory Reference" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BayerFilter/BayerFilter Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBayerFilterStream\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBayerFilterStream\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLImageFilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLImageFilter\&.h\fP"
.br
.ti -1c
.RI "file \fBOptions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOptions\&.h\fP"
.br
.in -1c
