.TH "BayerFilter/OpenCLInterface Directory Reference" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BayerFilter/OpenCLInterface Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOpenCLAlgorithm\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLAlgorithm\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLAlgorithmsStream\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLAlgorithmsStream\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLBayerFilter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLBayerFilter\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLDevice\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLDevice\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLException\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLException\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLFloatToInt\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLFloatToInt\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLHelpers\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLHelpers\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLIntToFloat\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLIntToFloat\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenCLInvertImage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenCLInvertImage\&.h\fP"
.br
.in -1c
