.TH "ConstructorTest" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstructorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSetDevice\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBOpenCLAlgorithm\fP * \fBal_ptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
