.TH "DeviceParameters" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeviceParameters \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.PP
Inherited by \fBBuildProgram\fP, \fBCommandQueue\fP, \fBDeviceContext\fP, and \fBIsValidTest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetDevs\fP ()"
.br
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::list< \fBOpenCLDevice\fP > \fBdevs\fP"
.br
.ti -1c
.RI "\fBOpenCLDevice\fP \fBempty_device\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
