.TH "JAI::CameraException" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JAI::CameraException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CameraException\&.h>\fP
.PP
Inherited by \fBJAI::NoNewFrameException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraException\fP (std::string mes='')"
.br
.ti -1c
.RI "\fBoperator std::string\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCamera\fP exception\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
