.TH "JAI::NoNewFrameException" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JAI::NoNewFrameException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJAI::CameraException\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
