.TH "OpenCLDeviceException" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLDeviceException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLDeviceException\fP (std::string m, int err=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
