.TH "OpenCLFloatToInt" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLFloatToInt \- 
.PP
Algorithm performs float to int conversion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenCLFloatToInt\&.h>\fP
.PP
Inherits \fBOpenCLImageAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLFloatToInt\fP (OpenCLFloatToIntMode mode=OpenCLFloatToIntMode::UINT8)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Algorithm performs float to int conversion\&. 

Possible output modes:
.IP "\(bu" 2
OpenCLFloatToIntMode::UINT8 - 8 bit unsigned int
.IP "\(bu" 2
OpenCLFloatToIntMode::UINT16 - 16 bit unsigned int
.IP "\(bu" 2
OpenCLFloatToIntMode::UINT32 - 32 bit unsigned int 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
