.TH "OpenCLInvertImage" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLInvertImage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP (const unsigned char *data_input, size_t di_size, unsigned char *data_output, size_t do_size)"
.br
.ti -1c
.RI "virtual void \fBprepare\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetParams\fP (const \fBOpenCLAlgorithmParams\fP &params)"
.br
.ti -1c
.RI "virtual void \fBsetParams\fP (const \fBOpenCLInvertImageParams\fP &params)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
