.TH "OpenCLBayerFilterParams" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLBayerFilterParams \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLAlgorithmParams\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLBayerFilterParams\fP (unsigned int width=0, unsigned int height=0, cl_uchar pattern=BFIOCL_PAT_RGR, int mode=BFIOCL_MODE_BGR, float red_b=1\&.0, float green_b=1\&.0, float blue_b=1\&.0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "cl_uchar \fBpattern\fP"
.br
.ti -1c
.RI "float \fBbalance\fP [3]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
