.TH "OpenCLIntToFloat" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLIntToFloat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenCLIntToFloat\&.h>\fP
.PP
Inherits \fBOpenCLImageAlgorithm\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Algorithm perfoming int to float conversion\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
