.TH "OpenCLImageFilter" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLImageFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenCLImageFilter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLImageFilter\fP (std::string filename, cl_uchar mode=BFIOCL_PAT_RGR)"
.br
.ti -1c
.RI "cv::Mat \fBgetInputImage\fP () const "
.br
.ti -1c
.RI "cv::Mat \fBgetOutputImage\fP ()"
.br
.ti -1c
.RI "cv::Mat \fBgetOutputImageOpenCV\fP ()"
.br
.ti -1c
.RI "void \fBsetInputImage\fP (const std::string filename)"
.br
.ti -1c
.RI "bool \fBsaveOutputImage\fP (std::string filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Example class for usage first version of OpenCLInterface\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
