.TH "OpenCLInvertImageParams" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLInvertImageParams \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLAlgorithmParams\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLInvertImageParams\fP (unsigned int w=0, unsigned int h=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
