.TH "OpenCLBayerFilterImage" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLBayerFilterImage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLBayerFilter\fP, and \fBOpenCLImageAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLBayerFilterImage\fP (BayerFilterMask mask_type=BayerFilterMask::SQUARE)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
