.TH "OpenCLBayerFilterFloat" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLBayerFilterFloat \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLBayerFilter\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
