.TH "OpenCLAlgorithmParams" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLAlgorithmParams \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOpenCLBayerFilterParams\fP, and \fBOpenCLInvertImageParams\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
