.TH "Options" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Options \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparseOptions\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Mode \fBmode\fP"
.br
.ti -1c
.RI "std::string \fBdirname\fP"
.br
.ti -1c
.RI "std::string \fBfilename\fP"
.br
.ti -1c
.RI "std::string \fBfilename_out\fP"
.br
.ti -1c
.RI "bool \fBopencv\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Options::parseOptions (intargc, char *argv[])"
Parse options sent to applications\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP Number of argument\&. 
.br
\fIargv\fP Argument values\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
