.TH "SetDevice" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetDevice \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.PP
Inherited by \fBConstructorTest\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpenCLAlgorithmTest\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBgetDevice\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBOpenCLDevice\fP \fBdevice\fP"
.br
.ti -1c
.RI "\fBOpenCLAlgorithmTest\fP \fBal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
