.TH "SetDevice::OpenCLAlgorithmTest" 3 "Tue Jan 8 2013" "BFIOCL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetDevice::OpenCLAlgorithmTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOpenCLAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpenCLAlgorithmTest\fP (const \fBOpenCLDevice\fP &dev)"
.br
.ti -1c
.RI "void \fBsetParams\fP (const \fBOpenCLAlgorithmParams\fP &params)"
.br
.ti -1c
.RI "void \fBprepare\fP (size_t di_size, size_t do_size)"
.br
.ti -1c
.RI "void \fBrun\fP (const unsigned char *data_input, size_t di_size, unsigned char *data_output, size_t do_size)"
.br
.ti -1c
.RI "void \fBsetKernelArgs\fP (size_t di_size, size_t do_size)"
.br
.ti -1c
.RI "void \fBreleaseMem\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for BFIOCL from the source code\&.
